config/routes.rb
Rails.application.routes.draw do

  root "static_pages#top"
  # デフォルトだとログイン後はrootパスに飛ぶ。
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: "omniauth_callbacks"
  }
  root to: 'static_pages#top' 


  # devise_scope :user do
    # TIPS: ユーザー登録しっぱいのリダイレクトのエラーを防ぐ https://github.com/heartcombo/devise/blob/master/app/controllers/devise/registrations_controller.rb
    # get '/users', to: 'users/registrations#new'
    # or
    # get '/users', to: redirect('/users/sign_up')
  # end

  resources :users, :only => [:index, :show, :destroy] do
    resources :tasks
    resources :requests do
      get 'edit_request'
      patch 'send_request'
      get 'check_requests'
      
      collection do
        patch 'finish_requests'      
      end
    end
  end
 
  # resources :users, :only => [:index, :show, :destroy] 
  # get '/users/:user_id/tasks/new', to: 'tasks#new'
  # post '/users/:user_id/tasks/create', to: 'tasks#create', as: :user_task_create
  # get '/users/:user_id/tasks', to: 'tasks#index', as: :user_tasks
  # get '/users/:user_id/tasks/:id', to: 'tasks#show', as: :user_task
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  # validates :description, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_user
  before_action :correct_user, only: [:index, :edit, :new, :create, :show, :destroy]

  def new
    @task = Task.new
  end

  def create
    @task = @user.tasks.new(task_params)
    params[:task][:status] = "未"
    if params[:task][:name].present?
      if params[:task][:deadline].nil? || params[:task][:deadline].blank?
        @task.save
        flash[:success] = "新規作成成功しました。"
        redirect_to user_tasks_url
      else      
        if params[:task][:deadline].to_date < Date.current
          flash[:danger] = "期日は本日以降の日付にして下さい"
          render :new
        else
          @task.save
          flash[:success] = "新規作成成功しました。"
          redirect_to user_tasks_url
        end
      end
    else 
      flash.now[:danger] = "タスク名を入力して下さい。"
      render :new      
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if params[:task][:name].present?
      if params[:task][:deadline].nil? || params[:task][:deadline].blank?
        @task.update(task_update_params)
        @task.save
        flash[:success] = "タスク情報を変更しました。"      
        redirect_to user_tasks_url @user      
      else
        if params[:task][:deadline].to_date < @task.created_at.to_date
          flash[:danger] = "期日はタスクの作成日以降の日付にして下さい"
          render :edit      
        else
          @task.update(task_update_params)
          @task.save
          flash[:success] = "タスク情報を変更しました。"
          redirect_to user_tasks_url @user
        end
      end
    else
      flash.now[:danger] = "タスク名を入力して下さい。"
      render :edit
    end
  end

  def index
    @tasks = @user.tasks.order(created_at: :desc)
  end

  def show
    @task = @user.tasks.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:success] = "削除に成功しました。"
      redirect_to user_tasks_url @user
  end

  private

    def set_user 
      @user = User.find(params[:user_id])
    end

    def task_params
      params.require(:task).permit(:name, :description, :status, :deadline)
    end

    def task_update_params
      params.require(:task).permit(:name, :description, :status, :deadline)
    end

    def current_user?(user)
      user == current_user
    end

    def correct_user
      unless current_user?(@user)
        flash[:danger] = "アクセスできません。"
        redirect_to root_url 
      end
    end


end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<% provide(:title, 'Edit Task') %>
<h1>タスク編集</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= form_with(model: @task, url: user_task_path(@user, @task), local: true, method: :patch) do |f| %>
      <%= render partial: 'shared/error_messages', locals: { obj: @task } %>
    
      <%= f.label :name, class: "label-task-edit" %>
      <%= f.text_field :name, class: "form-control" %>
      
      <%= f.label :description, class: "label-task-edit" %>
      <%= f.text_area :description, rows: 5, class: "form-control" %>

      <%= f.label :status, class: "label-task-edit" %>
      <%= f.select :status, ['未', '済'] %><br>
      
      <%= f.label :deadline, class: "label-task-edit" %>
      <%= f.date_field :deadline, class: "form-control" %>

      <%= f.submit "変更する",class: "btn btn-primary btn-lg btn-task-edit" %> 
    <% end %>
    <%= link_to "タスク一覧画面に戻る", user_tasks_path %>
  </div>
</div>

app/views/tasks/index.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %>のタスク一覧</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= link_to "タスク新規作成", new_user_task_path(@user), class: "btn btn-lg btn-primary pull-right" %>
    <table class="table table-hover" id="table-tasks">
      <thead>
        <tr>
          <th><%= Task.human_attribute_name :name %></th>
          <th><%= Task.human_attribute_name :description %></th>
          <th><%= Task.human_attribute_name :created_at %></th>
          <th><%= Task.human_attribute_name :status %></th>
          <th><%= Task.human_attribute_name :deadline %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @tasks.each do |task| %>
        <tr>
          <td><%= link_to task.name,user_task_path(@user, task), id: "task-name" %></td> 
          <td><%= task.description %></td>
          <td><%= l(task.created_at, format: :short) %></td>
          <td><%= task.status %></td>
          <td><%= l(task.deadline, format: :short, default: '-') %></td>
          <td>
            <%= link_to "編集", edit_user_task_path(@user, task), class: "btn btn-success" %>
            <%= link_to "削除", user_task_path(@user, task), method: :delete, data: {confirm: "「#{task.name}」を削除します。よろしいですか？"}, class: "btn btn-danger" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tasks/new.html.erb
<% provide(:title, 'New Task') %>
<h1>タスク新規作成</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= form_with(model: @task, url: user_tasks_path(@user), local: true) do |f| %>
      <%= render partial: 'shared/error_messages', locals: { obj: @task } %>
    
      <%= f.label :name, class: "label-task" %>
      <%= f.text_field :name, class: "form-control" %>
      
      <%= f.label :description, class: "label-task" %>
      <%= f.text_area :description, rows: 5, class: "form-control" %>

      <%= f.label :deadline, class: "label-task" %>
      <%= f.date_field :deadline, class: "form-control" %>      
      
      <%= f.submit "新規登録",class: "btn btn-primary btn-lg btn-task" %> 
    <% end %>
    <%= link_to "タスク一覧画面に戻る", user_tasks_path %>
  </div>
</div>

app/views/tasks/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %>のタスク詳細</h1>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <table class="table table-bordered" id="table-user">
      <tbody>
        <tr>
          <th class="active col-md-3"><%= Task.human_attribute_name :id %></th>
          <td class="col-md-9"><%= @task.id %></td>
        </tr>
        <tr>
          <th class="active"><%= Task.human_attribute_name :name %></th>
          <td><%= @task.name %></td>
        </tr>
        <tr> 
          <th class="active"><%= Task.human_attribute_name :description %></th>
          <td><%= @task.description %></td>
        </tr>
        <tr> 
          <th class="active"><%= Task.human_attribute_name :status %></th>
          <td><%= @task.status %></td>
        </tr>
        <tr> 
          <th class="active"><%= Task.human_attribute_name :deadline %></th>
          <td><%= l(@task.deadline, format: :short, default: '-') %></td>
        </tr>
        <tr>
          <th class="active"><%= Task.human_attribute_name :created_at %></th>
          <td><%= l(@task.created_at, format: :long) %></td>
        </tr>
        <tr>
          <th class="active"><%= Task.human_attribute_name :updated_at %></th>
          <td><%= l(@task.updated_at, format: :long) %></td>
        </tr>
        
      </tbody>
      
    </table>
    <div class="center">
      <%= link_to "編集", edit_user_task_path, class: "btn btn-lg btn-primary" %>
      <%= link_to "削除", user_task_path(@user, @task), method: :delete, data: {confirm: "「#{@task.name}」を削除します。よろしいですか？"}, class: "btn btn-lg btn-danger" %>
    </div>
  </div>    
</div>