config/routes.rb
Rails.application.routes.draw do

  root "static_pages#top"
  # デフォルトだとログイン後はrootパスに飛ぶ。
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: "omniauth_callbacks"
  }
  root to: 'static_pages#top' 


  # devise_scope :user do
    # TIPS: ユーザー登録しっぱいのリダイレクトのエラーを防ぐ https://github.com/heartcombo/devise/blob/master/app/controllers/devise/registrations_controller.rb
    # get '/users', to: 'users/registrations#new'
    # or
    # get '/users', to: redirect('/users/sign_up')
  # end

  resources :users, :only => [:index, :show, :destroy] do
    resources :tasks
    resources :requests do
      get 'edit_request'
      patch 'send_request'
      get 'check_requests'
      
      collection do
        patch 'finish_requests'      
      end
    end
  end
 
  # resources :users, :only => [:index, :show, :destroy] 
  # get '/users/:user_id/tasks/new', to: 'tasks#new'
  # post '/users/:user_id/tasks/create', to: 'tasks#create', as: :user_task_create
  # get '/users/:user_id/tasks', to: 'tasks#index', as: :user_tasks
  # get '/users/:user_id/tasks/:id', to: 'tasks#show', as: :user_task
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :requests, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 100 }
  validates :department, presence: true, length: { minimum:8, maximum: 100 }, allow_nil: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true              
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :omniauthable,
        #  deviseのバリデーションをなくす場合は、:validatableを消す（またはコメントアウトする）。deviseのバリデーション機能を使う場合は:validatableを記述する。
         :validatable, 
         omniauth_providers: %i[line]

  # 以下を追加
  def social_profile(provider)
    social_profiles.select { |sp| sp.provider == provider.to_s }.first
  end

  def set_values(omniauth)
    return if provider.to_s != omniauth["provider"].to_s || uid != omniauth["uid"]
    credentials = omniauth["credentials"]
    info = omniauth["info"]

    access_token = credentials["refresh_token"]
    access_secret = credentials["secret"]
    credentials = credentials.to_json
    name = info["name"]
    # self.set_values_by_raw_info(omniauth['extra']['raw_info'])
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end

  # 以上を追加

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank? 
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  def update_resource(resource, params)
    resource.update_without_current_password(params) #独自のメソッド。解説は下記にて。
  end
  
  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(resource)
  end


  # マイページを更新した後のパス
  def after_update_path_for(resource)
    user_path(current_user)
  end  
  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :destroy]
  before_action :admin_user, only: [:index, :destroy]
  before_action :no_department_user, only: []
  # before_action :correct_user, only: [:show]


  def index
    @users = User.all.paginate(page: params[:page], per_page: 5)
    
  end

  def show
    @user = User.find(params[:id])
    @requests = @user.requests.where.not(request_status: nil)
    @recieve_requests = Request.where(partner_number: @user.id).where(request_status: "未")
    @recieve_finished_requests = @user.requests.where.not(partner_number: @user.id).where(request_status: "実施済み").where(request_change_status: true)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_path
  end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def correct_user
      unless current_user?(@user)
        flash[:danger] = "アクセスできません。"
        redirect_to root_url 
      end
    end

        

end

app/helpers/users_helper.rb
module UsersHelper

	# 渡されたユーザーがログイン済みのユーザーであればtrueを返します。
	def current_user?(user)
		user == current_user
	end    
end

app/views/users/index.html.erb
<% provide(:title,'Users') %>
<h1>利用者一覧</h1>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= will_paginate %>
    <table class="table table-condensed table-hover">
      <thead>
        <tr>
          <th><%= User.human_attribute_name :name %></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name,user_path(user) %>
          	<% if user.admin? %>
            	<span class="label label-primary label-user-division">管理者</span>
          	<% else %> 
            	<span class="label label-success label-user-division">一般</span>
					 	<% end %>
          </td>
          <td>
          
 					<% if current_user.admin? && !current_user?(user) %> 

            <%= link_to "削除", user_path(user), method: :delete,
            data: {confirm:"#{user.name}を削除します。よろしいですか？"},
            class:"btn btn-danger btn-sm pull-right" %>
 					<% end %>  
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate %>
</div>  

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %>さんの My Page</h1>
<% unless current_user.admin? && @user != current_user %>
  <% if @recieve_requests.count > 0 %>
    <h1><%= link_to "#{@recieve_requests.count}件のリクエストがあります", user_request_check_requests_path(@user, @requests), class: "btn btn-lg btn-danger" %></h1>
  <% end %>
  <% if @recieve_finished_requests.count > 0 %>
    <h2 class="text-success"><%= "#{@recieve_finished_requests.count}件のリクエスト完了通知があります。リクエスト一覧から一覧から確認して下さい。" %></h1>
  <% end %>
<% end %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table table-bordered" id="table-user">
      <tbody>

        <tr>
          <th class="active"><%= User.human_attribute_name :name %></th>
          <td><%= @user.name %></td>
        </tr>
        <tr> 
          <th class="active"><%= User.human_attribute_name :email %></th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th class="active col-md-3"><%= User.human_attribute_name :department %></th>
          <td class="col-md-9"><%= @user.department %></td>
        </tr>        
        <tr>
          <th class="active"><%= User.human_attribute_name :created_at %></th>
          <td><%= l(@user.created_at, format: :long) %></td>
        </tr>
      </tbody>
    </table>
  </div>  
</div>
<div class="center">
  <% unless current_user.admin? && current_user != @user %>
  <%= link_to "タスク一覧",user_tasks_path(@user) ,class: "btn btn-lg btn-primary" %>
    <% if current_user.department.present? %>    
      <%= link_to "リクエスト一覧",user_requests_path(@user) ,class: "btn btn-lg btn-success" %>
    <% else %>
      <%= link_to "リクエスト一覧",user_requests_path(@user) ,class: "btn btn-lg btn-success disabled" %>
    <% end %>
  <% end %>
</div>  