config/routes.rb
Rails.application.routes.draw do

  root "static_pages#top"
  # デフォルトだとログイン後はrootパスに飛ぶ。
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: "omniauth_callbacks"
  }
  root to: 'static_pages#top' 


  # devise_scope :user do
    # TIPS: ユーザー登録しっぱいのリダイレクトのエラーを防ぐ https://github.com/heartcombo/devise/blob/master/app/controllers/devise/registrations_controller.rb
    # get '/users', to: 'users/registrations#new'
    # or
    # get '/users', to: redirect('/users/sign_up')
  # end

  resources :users, :only => [:index, :show, :destroy] do
    resources :tasks
    resources :requests do
      get 'edit_request'
      patch 'send_request'
      get 'check_requests'
      
      collection do
        patch 'finish_requests'      
      end
    end
  end
 
  # resources :users, :only => [:index, :show, :destroy] 
  # get '/users/:user_id/tasks/new', to: 'tasks#new'
  # post '/users/:user_id/tasks/create', to: 'tasks#create', as: :user_task_create
  # get '/users/:user_id/tasks', to: 'tasks#index', as: :user_tasks
  # get '/users/:user_id/tasks/:id', to: 'tasks#show', as: :user_task
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  
  validates :request_name, presence: true
  validates :request_description, presence: true  

  # リクエスト新規作成の際、期日が本日よりも前の日付の場合に無効
  validate :request_time_check

  # リクエスト編集の際、期日が作成日よりも前の日付の場合に日付の場合に

  def request_time_check
    errors.add(:request_deadline, "は本日以降を選択してください。") if self.request_deadline.nil? || self.request_deadline.blank? || (self.request_deadline < Date.current)
  end
  
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_user
  before_action :correct_user
  before_action :no_department_user

  def new
    @request = Request.new
  end

  def create
    @request = @user.requests.new(request_params)
    
    params[:request][:request_status] = "未"
    if @request.save
      flash[:success] = "新規作成成功しました。"
      redirect_to user_requests_url
    else
      render :new
    end
  end   

# 以前に作成した自作のcreateアクション。ifやunlessが多く、見づらいため新しいアクションを作成してみる　
  # def create
  #   @request = @user.requests.new(request_params)
    
  #   params[:request][:request_status] = "未"
  #   if params[:request][:request_name].present? && params[:request][:request_description].present?
  #     unless params[:request][:request_deadline].nil? || params[:request][:request_deadline].blank?
  #       if params[:request][:request_deadline].to_date < Date.current 
  #         flash[:danger] = "本日以降の期日を設定して下さい。"
  #         render :new
  #       else
  #         @request.save
  #         flash[:success] = "新規作成成功しました。"
  #         redirect_to user_requests_url
  #       end
  #     else
  #       flash[:danger] = "本日以降の期日を設定して下さい。"
  #       render :new
  #     end
  #   else
  #     flash[:danger] = "リクエスト名とリクエスト詳細は入力必須です。"
  #     render :new
  #   end
  # end   

  def index
    @user = User.find(params[:user_id])
    @requests = @user.requests.order(created_at: :desc)
  end

  def edit
    @request = Request.find(params[:id])
  end

  # def update
  #   @request = Request.find(params[:id])
  #   if params[:request][:request_deadline].blank? || params[:request][:request_deadline].to_date < Date.current
  #     flash[:danger] = "本日以降の期日を入力して下さい。"
  #     redirect_to edit_user_request_path(@user, @request) and return
  #   else
  #     @request.update(request_params)
  #     flash[:success] = "リクエストを変更しました"
  #     redirect_to user_requests_path(@user)
  #   end
  # end

  def update
    @request = Request.find(params[:id])
    if @request.update(request_params)
      flash[:success] = "リクエストを変更しました"
      redirect_to user_requests_path(@user)
    else
     render :edit      
    end
  end

  # createアクションの作り直しが成功したのとrequest.rbにうまく記述できたことを受けて、updateアクションを作り直す
  # def update
  #   @request = Request.find(params[:id])
  #   unless params[:request][:request_deadline].blank? || params[:request][:request_deadline].to_date < Date.current
  #     @request.update(request_params)
  #     flash[:success] = "リクエストを変更しました"
  #     redirect_to user_requests_path(@user)
  #   else
  #     flash[:danger] = "本日以降の期日を入力して下さい。"
  #     redirect_to edit_user_request_path(@user, @request)     
  #   end
  # end

  def edit_request
    @request = Request.find(params[:request_id])
    @partners = User.where(partner: true).where(department: @user.department).where.not(id: @user.id)
  end

  def send_request
    @request = Request.find(params[:request_id])
    if send_request_params[:partner_number].blank?
      
     flash[:danger] = "依頼先を選択して下さい。"
     redirect_to user_request_edit_request_path(@user, @request) and return
   else
     @request.update(send_request_params)
     @partner = User.find(@request.partner_number)
     flash[:success] = "#{@partner.name}にタスクを依頼しました。"
     
   end
    redirect_to user_requests_url(@user)
  end

  def check_requests
    @requests = Request.where(partner_number: @user.id).where(request_status: "未").order(:request_deadline).group_by(&:user_id)
  end

  def finish_requests
    c1 = 0
    ActiveRecord::Base.transaction do # トランザクションを開始します。
      finish_request_params.each do |id, item|
        request = Request.find(id)
        if item[:request_change_status] == "1"
          if item[:request_status] == "未"
            item[:request_change_status] = nil
          end
          c1 += 1
          request.update!(item)
        end
      end
    end
    flash[:success] = "#{c1}件のリクエストを実施済みに変更しました。"
    redirect_to @user
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
    flash[:danger] = "無効な入力データがあった為、リクエスト処理をキャンセルしました。"
    redirect_to @user   
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    flash[:success] = "リクエストの削除に成功しました。"
      redirect_to user_requests_url @user
  end

  private

  def set_user 
    @user = User.find(params[:user_id])
  end

  def request_params
    params.require(:request).permit(:request_name, :request_description, :request_status, :request_deadline)
  end   

  def send_request_params
    params.require(:request).permit(:partner_number)
  end

  def finish_request_params
    params.require(:user).permit(requests: [:request_status, :request_change_status])[:requests]
  end

  def no_department_user
    unless current_user.department.present?
      flash[:warning] = "リクエスト機能は家族IDを設定してから利用可能です。"
      redirect_to user_path(@user)
    end
  end 
  
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/check_requests.html.erb
<% provide(:title, "リクエスト確認") %>
<% provide(:button_text, "更新する") %> 
      <div class="row">
        <div class="col-md-10 col-md-offset-1">

        
        <%= form_with(model: @user, url: finish_requests_user_requests_path(@user), local: true, method: :patch) do |f| %>
        <% @requests.each do |id, requests| %>
           <% user = User.find(id) %> 

          <table class="table table-bordered table-condensed">
            <thead>
              <tr>
								<h1><%= user.name %>からのリクエスト</h1> 
                <th><%= Request.human_attribute_name :request_deadline %></th>
                <th><%= Request.human_attribute_name :request_name %></th>
                <th><%= Request.human_attribute_name :request_description %></th>
                <th><%= Request.human_attribute_name :request_status %></th>
								<th><%= Request.human_attribute_name :request_change_status %></th>
							</tr>
              </thead>
              <tbody>
                <% requests.each do |request| %>
                <%# 
                  day_of_week_color = case $days_of_the_week[day.worked_on.wday]
                  when "土"
                    "text-primary"
                  when "日"
                    "text-danger"
                  end 
                %>
                <%= f.fields_for "requests[]", request do |item| %>
                <tr>
                  <td><%= l(request.request_deadline, format: :short) %></td>
                  <td><%= request.request_name %></td>
                  <td><%= request.request_description %></td>
                  <td>
                    <%= item.select :request_status, ['未', '実施済み'] %>
                  </td>
                  <td><%= item.check_box :request_change_status %></td>
                </tr>
                <% end %>
                <% end %>
              </tbody>              
            </table>
						<% end %>
            <table>
              <div class="center footer-button">
                <%= f.submit yield(:button_text), class: "btn btn-lg btn-primary" %>
              </div>
            </table>   
          <% end %>
          </div>
        </div>

app/views/requests/edit.html.erb
<% provide(:title, 'Edit Request') %>
<h1>リクエスト編集</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= form_with(model: @request, url: user_request_path(@user, @request), local: true, method: :patch) do |f| %>
      <%= render partial: 'shared/error_messages', locals: { obj: @request } %>
    
      <%= f.label :request_name, class: "label-request-edit" %>
      <%= f.text_field :request_name, class: "form-control" %>
      
      <%= f.label :request_description, class: "label-request-edit" %>
      <%= f.text_area :request_description, rows: 5, class: "form-control" %>

      <%#= f.label :request_status, class: "label-request-edit" %>
      <%#= f.select :request_status, ['未', '済'] %><br>
      
      <%= f.label :request_deadline, class: "label-request-edit" %>
      <%= f.date_field :request_deadline, class: "form-control" %>

      <%= f.submit "変更する",class: "btn btn-primary btn-lg btn-request-edit" %> 
    <% end %>
    <%= link_to "リクエスト一覧画面に戻る", user_requests_path %>
  </div>
</div>

app/views/requests/edit_request.html.erb
<% provide(:title, "リクエスト送信") %>
<% provide(:button_text, "リクエスト送信する") %> 
    <h1><%= @user.name %>の<%= @request.request_name %>をリクエスト送信</h1>
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <%= form_with(model: @request, url: user_request_send_request_path(@user, @request), local: true, method: :patch) do |f| %>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th><%= Request.human_attribute_name :request_name %></th>
                  <th><%= Request.human_attribute_name :request_description %></th>
                  <th><%#= Request.human_attribute_name :request_status %></th>
                  <th><%= Request.human_attribute_name :request_deadline %></th>
									<th><%= Request.human_attribute_name :partner_number %></th>
                </tr>
              </thead>
      
              <tbody>
								<tr>
                  <td><%= @request.request_name %></td>
                  <td><%= @request.request_description %></td>
                  <td><%#= @request.request_status %></td>
                  <td><%= l(@request.request_deadline, format: :short) %> </td>
                  <td>
                    <%= f.collection_select(:partner_number, @partners, :id, :name, { include_blank: "選択して下さい。" }) %> 
                  </td>
                </tr>
              </tbody>
            </table>
            <div class="center">
              <%= f.submit yield(:button_text), class:"btn btn-lg btn-block btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>

app/views/requests/index.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %>のリクエスト一覧</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= link_to "リクエスト新規作成", new_user_request_path(@user), class: "btn btn-lg btn-primary pull-right" %>
    <table class="table table-hover" id="table-requests">
      <thead>
        <tr>
          <th><%= Task.human_attribute_name :request_name %></th>
          <th><%= Task.human_attribute_name :request_description %></th>
          <th><%= Task.human_attribute_name :created_at %></th>
          <th><%= Task.human_attribute_name :request_deadline %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @requests.each do |request| %>
        <% if request.request_status == "実施済み" %>
				<tr class="bg-success">
          <td><%= request.request_name %><%#= link_to request.name,user_task_path(@user, task), id: "task-name" %></td> 
          <td><%= request.request_description %></td>
          <td><%= l(request.created_at, format: :short) %></td>
          <td><%= request.request_deadline %></td>
          <td>リクエスト完了
        	</td>
          <td>
            <%= link_to "削除", user_request_path(@user, request), method: :delete, data: {confirm: "「#{request.request_name}」を削除します。よろしいですか？"}, class: "btn btn-danger" %>
          </td>
        </tr>
				<% else %>
				<tr>
          <td><%= request.request_name %><%#= link_to request.name,user_task_path(@user, task), id: "task-name" %></td> 
          <td><%= request.request_description %></td>
          <td><%= l(request.created_at, format: :short) %></td>
          <td><%= request.request_deadline %><%#= l(request.request_deadline, format: :middle) %></td>
          <td>
					<% if request.partner_number.nil? %>
          	<%= link_to "リクエスト依頼", user_request_edit_request_path(@user, request), class: "btn btn-primary" if current_user == @user %>
					<% else %>
						リクエスト依頼中
					<% end %>
        	</td>
          <td>
            <%= link_to "変更", edit_user_request_path(@user, request), class: "btn btn-success" %>
            <%= link_to "削除", user_request_path(@user, request), method: :delete, data: {confirm: "「#{request.request_name}」を削除します。よろしいですか？"}, class: "btn btn-danger" %>
          </td>
        </tr>
				<% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/requests/new.html.erb
<% provide(:title, 'New Task') %>
<h1>リクエスト新規作成</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= form_with(model: @request, url: user_requests_path(@user), local: true) do |f| %>
      <%= render partial: 'shared/error_messages', locals: { obj: @request } %>
    
      <%= f.label :request_name, class: "label-request" %>
      <%= f.text_field :request_name, class: "form-control" %>
      
      <%= f.label :request_description, class: "label-request" %>
      <%= f.text_area :request_description, rows: 3, class: "form-control" %>

      <%= f.label :request_deadline, class: "label-request" %>
      <%= f.date_field :request_deadline, class: "form-control" %>      
      
      <%= f.submit "リクエスト一覧に送る",class: "btn btn-primary btn-lg btn-request" %> 
    <% end %>
    <%= link_to "リクエスト一覧画面に戻る", user_requests_path %>
  </div>
</div>