config/routes.rb
Rails.application.routes.draw do

  root "static_pages#top"
  # デフォルトだとログイン後はrootパスに飛ぶ。
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: "omniauth_callbacks"
  }
  root to: 'static_pages#top' 


  # devise_scope :user do
    # TIPS: ユーザー登録しっぱいのリダイレクトのエラーを防ぐ https://github.com/heartcombo/devise/blob/master/app/controllers/devise/registrations_controller.rb
    # get '/users', to: 'users/registrations#new'
    # or
    # get '/users', to: redirect('/users/sign_up')
  # end

  resources :users, :only => [:index, :show, :destroy] do
    resources :tasks
    resources :requests do
      get 'edit_request'
      patch 'send_request'
      get 'check_requests'
      
      collection do
        patch 'finish_requests'      
      end
    end
  end
 
  # resources :users, :only => [:index, :show, :destroy] 
  # get '/users/:user_id/tasks/new', to: 'tasks#new'
  # post '/users/:user_id/tasks/create', to: 'tasks#create', as: :user_task_create
  # get '/users/:user_id/tasks', to: 'tasks#index', as: :user_tasks
  # get '/users/:user_id/tasks/:id', to: 'tasks#show', as: :user_task
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Task管理・Task依頼アプリ", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "トップ", root_path %></li>
        <% if user_signed_in?	 %>
          <% if current_user.admin? %>
            <li><%= link_to "利用者一覧", users_path %></li>
          <% end %>
          <li><%#= link_to "タスク作成", new_user_task_path(current_user) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li class="active dropdown-header">ユーザー</li>
              <li><%= link_to "マイページ", user_path(current_user) %></li>
              <li><%= link_to "プロフィール設定", edit_user_registration_path %></li>
              <li class="active dropdown-header">タスク</li>
              <li><%= link_to "タスク一覧", user_tasks_path(current_user) %></li>
              <li><%= link_to "タスク新規作成", new_user_task_path(current_user) %></li>
                <%# if current_user.department.present? %>
                <li class="active dropdown-header">リクエスト</li>
                <% if current_user.department.present? %>     
                  <li><%= link_to "リクエスト一覧", user_requests_path(current_user) %></li>
                  <li><%= link_to "リクエスト新規作成", new_user_request_path(current_user) %></li>
                <% else %>
                  <li><%= link_to "リクエスト一覧", user_requests_path(current_user), class: "btn disabled" %></li>
                  <li><%= link_to "リクエスト新規作成", new_user_request_path(current_user), class: "btn disabled" %></li>
                <% end %>              
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <% flash.each do |message_type, msg| %>
    <div class="alert alert-<%= message_type %>"><%= msg %></div>
    <% end %>

    <%
=begin%>
 <% flash.each do |key, value| %>
      <div class="alert alert-<%= bootstrap_alert(key) %>">
        <strong>
          <%= value %>
        </strong>
      </div>
      <% end %> 
<%
=end%>
   
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>